### ISSUE TITLE
Does not work with TensorFlow 2.16.1

### ISSUE THREAD

**Issue by Szubie** [beringresearch/ivis#123]
[TensorFlow 2.16.1 recently released](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1), but using it will break ivis workflows.

See error log from running tests [here](https://github.com/beringresearch/ivis/actions/runs/8222082994/job/22483178136).

Error list:
- ValueError: The layer sequential has never been called and thus has no defined output.
- AttributeError: 'Adam' object has no attribute 'get_weights'

Warnings to make sure are not a problem:
- UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.

Might be worth pinning the tensorflow version ivis uses to a known good version.

**Comment by aitor-martinez-seras** [comment]
Error still happening, resolved downgrading as mentioned (to tensorflow 2.15.0 in my case)

**Comment by Szubie** [comment]
Thanks for the update. I've restricted the Tensorflow version in setup.py (and requirements.txt) to ensure only versions below 2.16 are installed when running commands like `pip install ivis[cpu]` or `pip install ivis[gpu]`.
